name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          check-latest: true
          cache: npm

      - name: Cache Node modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Cache setup
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}

  run:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [lint, test]
    steps:
      - name: Restore setup
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Run ${{ matrix.command }} task
        run: yarn ${{ matrix.command }}
